
# travis config

dist: trusty
language: r
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release

before_install:
  - R -e "install.packages(c('settings','loadr','roxygen2','testthat','knitr'))"
  - R -e "loadr::load_all('./pkg'); roxygen2::roxygenize('./pkg')"
  - cd ./pkg

r_packages:
  - covr
  - rmarkdown


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


