language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - cp ./build/DESCRIPTION ./pkg
  - cd ./pkg
  - ../travis-tool.sh install_deps
  - ../travis-tool.sh install_r roxygen2
  - R -e "roxygen2::update_collate('.');devtools::document()"
  - ../travis-tool.sh github_package jimhester/covr
script: 
  - ../travis-tool.sh run_tests
after_failure:
  - ../travis-tool.sh dump_logs
after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
